export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_MESSAGES_LOADING = "SET_MESSAGES_LOADING";
